---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-stocks
  name: hello-stocks
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-stocks
      version: v1
  template:
    metadata:
      labels:
        app: hello-stocks
        version: v1
    spec:
      containers:
        - name: hello-stocks
          image: hello:latest
          imagePullPolicy: Never
          env:
          - name: GIN_MODE
            value: release
          - name: HOSTPORT
            value: :8080
          ports:
          - name: service-port
            containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: service-port
            initialDelaySeconds: 15
            periodSeconds: 20

