---
apiVersion: v1
kind: Service
metadata:
  name: hello-stocks
  namespace: default
spec:
  selector:
    app: hello-stocks
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
